### ISSUE TITLE
Investigate replacing foreman with matchbox + dnsmasq

### ISSUE THREAD

**Issue by fabianvf** [fabianvf/home-cluster#19]
Related to #18 

If we switch from Atomic to CoreOS, it may make sense to look into using the existing infrastructure for managing CoreOS clusters. This would allow us to move to an entirely containerized infrastructure, and may even allow us to run the openshift-master on the same server as the DNS - removing the need for a spare server for running foreman. This would let us go from 3 (nodes) + 1 (foreman) requirement to just the 3 nodes. If we added support for rook.io instead of glusterfs, it might even let us get to a single server for everything.

**Comment by fabianvf** [comment]
https://github.com/coreos/matchbox

**Comment by LorbusChris** [comment]
I like the idea.

A few related questions:
Is there a way to still support Atomic with Matchbox? (I'm a big fan of atomic's rollback functionality)
Is there a need for something like Pulp 3 for image/repository management?
I plan to use FreeIPA as user db and possibly for DNS of deployed services, but it's not clear to me yet how to achieve the DNS part. 

Any thoughts and/or objections on this? :)

**Comment by fabianvf** [comment]
Honestly this is more of a question than anything, I know very little about matchbox but I was looking into the CoreOS stuff a little more and thought it merited investigation. 

- Support for atomic is possible with matchbox AFAICT. I'm waiting to see if the CoreOS acquisition leads to atomic's death though, if RH drops support I probably will too.

- Pulp is cool, but might be a little heavyweight for the low end servers I'm looking at running the cluster on. I tried syncing a repo with Katello (pulp on the backend) and the whole thing fell over pretty hard. Definitely interested in it though, would be a good optional role.

- For using FreeIPA for DNS of deployed services, you'd just need to add a wildcard redirect of your cluster subdomain to the master, similar to [what I'm doing for Foreman's DNS](https://github.com/fabianvf/home-cluster/blob/master/roles/foreman/tasks/main.yml#L107). I don't know much about FreeIPA either.

**Comment by fabianvf** [comment]
Going to replace with our own TFTP server + openshift dns
